#if (clock=0)  // 2a0
    #declare SubspaceVerticesPositive = array[2]{2, 4};
    #declare SubspaceVertexWeight = 2;
    #declare SubspaceEdges = array[4]{array[2]{2, -4}, array[2]{-2, -4}, array[2]{-2, 4}, array[2]{2, 4}};
    #declare SubspaceEdgeWeights = array[4]{1, 1, 1, 1};
    #declare SubspaceFaces = array[1]{array[4]{-2, -4, 2, 4}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=1)  // 2a1
    #declare SubspaceVerticesPositive = array[2]{8, 10};
    #declare SubspaceVertexWeight = 2;
    #declare SubspaceEdges = array[4]{array[2]{8, -10}, array[2]{-8, -10}, array[2]{-8, 10}, array[2]{8, 10}};
    #declare SubspaceEdgeWeights = array[4]{1, 1, 1, 1};
    #declare SubspaceFaces = array[1]{array[4]{-8, -10, 8, 10}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=2)  // 2a2
    #declare SubspaceVerticesPositive = array[2]{6, 12};
    #declare SubspaceVertexWeight = 2;
    #declare SubspaceEdges = array[4]{array[2]{6, -12}, array[2]{-6, -12}, array[2]{-6, 12}, array[2]{6, 12}};
    #declare SubspaceEdgeWeights = array[4]{1, 1, 1, 1};
    #declare SubspaceFaces = array[1]{array[4]{-6, -12, 6, 12}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=3)  // 2a3
    #declare SubspaceVerticesPositive = array[2]{26, 28};
    #declare SubspaceVertexWeight = 2;
    #declare SubspaceEdges = array[4]{array[2]{26, -28}, array[2]{-26, -28}, array[2]{-26, 28}, array[2]{26, 28}};
    #declare SubspaceEdgeWeights = array[4]{1, 1, 1, 1};
    #declare SubspaceFaces = array[1]{array[4]{-26, -28, 26, 28}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=4)  // 2a4
    #declare SubspaceVerticesPositive = array[2]{24, 30};
    #declare SubspaceVertexWeight = 2;
    #declare SubspaceEdges = array[4]{array[2]{24, -30}, array[2]{-24, -30}, array[2]{-24, 30}, array[2]{24, 30}};
    #declare SubspaceEdgeWeights = array[4]{1, 1, 1, 1};
    #declare SubspaceFaces = array[1]{array[4]{-24, -30, 24, 30}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=5)  // 2a5
    #declare SubspaceVerticesPositive = array[2]{18, 36};
    #declare SubspaceVertexWeight = 2;
    #declare SubspaceEdges = array[4]{array[2]{18, -36}, array[2]{-18, -36}, array[2]{-18, 36}, array[2]{18, 36}};
    #declare SubspaceEdgeWeights = array[4]{1, 1, 1, 1};
    #declare SubspaceFaces = array[1]{array[4]{-18, -36, 18, 36}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=6)  // 2b00
    #declare SubspaceVerticesPositive = array[2]{5, 7};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[4]{array[2]{5, -7}, array[2]{5, 7}, array[2]{-5, 7}, array[2]{-5, -7}};
    #declare SubspaceEdgeWeights = array[4]{1, 2, 1, 2};
    #declare SubspaceFaces = array[1]{array[4]{-5, -7, 5, 7}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=7)  // 2b01
    #declare SubspaceVerticesPositive = array[2]{5, 11};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[4]{array[2]{5, 11}, array[2]{5, -11}, array[2]{-5, -11}, array[2]{-5, 11}};
    #declare SubspaceEdgeWeights = array[4]{2, 1, 2, 1};
    #declare SubspaceFaces = array[1]{array[4]{-5, 11, 5, -11}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=8)  // 2b02
    #declare SubspaceVerticesPositive = array[2]{7, 11};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[4]{array[2]{-7, 11}, array[2]{-7, -11}, array[2]{7, -11}, array[2]{7, 11}};
    #declare SubspaceEdgeWeights = array[4]{2, 1, 2, 1};
    #declare SubspaceFaces = array[1]{array[4]{7, 11, -7, -11}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=9)  // 2b03
    #declare SubspaceVerticesPositive = array[2]{5, 13};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[4]{array[2]{5, -13}, array[2]{-5, -13}, array[2]{-5, 13}, array[2]{5, 13}};
    #declare SubspaceEdgeWeights = array[4]{2, 1, 2, 1};
    #declare SubspaceFaces = array[1]{array[4]{-5, -13, 5, 13}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=10)  // 2b04
    #declare SubspaceVerticesPositive = array[2]{7, 13};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[4]{array[2]{-7, -13}, array[2]{7, -13}, array[2]{7, 13}, array[2]{-7, 13}};
    #declare SubspaceEdgeWeights = array[4]{2, 1, 2, 1};
    #declare SubspaceFaces = array[1]{array[4]{7, -13, -7, 13}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=11)  // 2b05
    #declare SubspaceVerticesPositive = array[2]{11, 13};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[4]{array[2]{11, -13}, array[2]{-11, -13}, array[2]{-11, 13}, array[2]{11, 13}};
    #declare SubspaceEdgeWeights = array[4]{1, 2, 1, 2};
    #declare SubspaceFaces = array[1]{array[4]{-11, -13, 11, 13}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=12)  // 2b06
    #declare SubspaceVerticesPositive = array[2]{23, 25};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[4]{array[2]{23, -25}, array[2]{23, 25}, array[2]{-23, 25}, array[2]{-23, -25}};
    #declare SubspaceEdgeWeights = array[4]{1, 2, 1, 2};
    #declare SubspaceFaces = array[1]{array[4]{-23, -25, 23, 25}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=13)  // 2b07
    #declare SubspaceVerticesPositive = array[2]{23, 29};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[4]{array[2]{23, 29}, array[2]{23, -29}, array[2]{-23, -29}, array[2]{-23, 29}};
    #declare SubspaceEdgeWeights = array[4]{2, 1, 2, 1};
    #declare SubspaceFaces = array[1]{array[4]{-23, 29, 23, -29}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=14)  // 2b08
    #declare SubspaceVerticesPositive = array[2]{25, 29};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[4]{array[2]{-25, 29}, array[2]{-25, -29}, array[2]{25, -29}, array[2]{25, 29}};
    #declare SubspaceEdgeWeights = array[4]{2, 1, 2, 1};
    #declare SubspaceFaces = array[1]{array[4]{25, 29, -25, -29}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=15)  // 2b09
    #declare SubspaceVerticesPositive = array[2]{23, 31};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[4]{array[2]{23, -31}, array[2]{-23, -31}, array[2]{-23, 31}, array[2]{23, 31}};
    #declare SubspaceEdgeWeights = array[4]{2, 1, 2, 1};
    #declare SubspaceFaces = array[1]{array[4]{-23, -31, 23, 31}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=16)  // 2b10
    #declare SubspaceVerticesPositive = array[2]{25, 31};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[4]{array[2]{-25, -31}, array[2]{25, -31}, array[2]{25, 31}, array[2]{-25, 31}};
    #declare SubspaceEdgeWeights = array[4]{2, 1, 2, 1};
    #declare SubspaceFaces = array[1]{array[4]{25, -31, -25, 31}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=17)  // 2b11
    #declare SubspaceVerticesPositive = array[2]{29, 31};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[4]{array[2]{29, -31}, array[2]{-29, -31}, array[2]{-29, 31}, array[2]{29, 31}};
    #declare SubspaceEdgeWeights = array[4]{1, 2, 1, 2};
    #declare SubspaceFaces = array[1]{array[4]{-29, -31, 29, 31}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=18)  // 2b12
    #declare SubspaceVerticesPositive = array[2]{17, 19};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[4]{array[2]{17, -19}, array[2]{17, 19}, array[2]{-17, 19}, array[2]{-17, -19}};
    #declare SubspaceEdgeWeights = array[4]{1, 2, 1, 2};
    #declare SubspaceFaces = array[1]{array[4]{-17, -19, 17, 19}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=19)  // 2b13
    #declare SubspaceVerticesPositive = array[2]{17, 35};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[4]{array[2]{17, 35}, array[2]{17, -35}, array[2]{-17, -35}, array[2]{-17, 35}};
    #declare SubspaceEdgeWeights = array[4]{2, 1, 2, 1};
    #declare SubspaceFaces = array[1]{array[4]{-17, 35, 17, -35}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=20)  // 2b14
    #declare SubspaceVerticesPositive = array[2]{19, 35};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[4]{array[2]{-19, 35}, array[2]{-19, -35}, array[2]{19, -35}, array[2]{19, 35}};
    #declare SubspaceEdgeWeights = array[4]{2, 1, 2, 1};
    #declare SubspaceFaces = array[1]{array[4]{19, 35, -19, -35}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=21)  // 2b15
    #declare SubspaceVerticesPositive = array[2]{17, 37};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[4]{array[2]{17, -37}, array[2]{-17, -37}, array[2]{-17, 37}, array[2]{17, 37}};
    #declare SubspaceEdgeWeights = array[4]{2, 1, 2, 1};
    #declare SubspaceFaces = array[1]{array[4]{-17, -37, 17, 37}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=22)  // 2b16
    #declare SubspaceVerticesPositive = array[2]{19, 37};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[4]{array[2]{-19, -37}, array[2]{19, -37}, array[2]{19, 37}, array[2]{-19, 37}};
    #declare SubspaceEdgeWeights = array[4]{2, 1, 2, 1};
    #declare SubspaceFaces = array[1]{array[4]{19, -37, -19, 37}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=23)  // 2b17
    #declare SubspaceVerticesPositive = array[2]{35, 37};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[4]{array[2]{35, -37}, array[2]{-35, -37}, array[2]{-35, 37}, array[2]{35, 37}};
    #declare SubspaceEdgeWeights = array[4]{1, 2, 1, 2};
    #declare SubspaceFaces = array[1]{array[4]{-35, -37, 35, 37}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=24)  // 2b18
    #declare SubspaceVerticesPositive = array[2]{15, 21};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[4]{array[2]{15, -21}, array[2]{15, 21}, array[2]{-15, 21}, array[2]{-15, -21}};
    #declare SubspaceEdgeWeights = array[4]{1, 2, 1, 2};
    #declare SubspaceFaces = array[1]{array[4]{-15, -21, 15, 21}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=25)  // 2b19
    #declare SubspaceVerticesPositive = array[2]{15, 33};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[4]{array[2]{15, 33}, array[2]{15, -33}, array[2]{-15, -33}, array[2]{-15, 33}};
    #declare SubspaceEdgeWeights = array[4]{2, 1, 2, 1};
    #declare SubspaceFaces = array[1]{array[4]{-15, 33, 15, -33}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=26)  // 2b20
    #declare SubspaceVerticesPositive = array[2]{21, 33};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[4]{array[2]{-21, 33}, array[2]{-21, -33}, array[2]{21, -33}, array[2]{21, 33}};
    #declare SubspaceEdgeWeights = array[4]{2, 1, 2, 1};
    #declare SubspaceFaces = array[1]{array[4]{21, 33, -21, -33}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=27)  // 2b21
    #declare SubspaceVerticesPositive = array[2]{15, 39};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[4]{array[2]{15, -39}, array[2]{-15, -39}, array[2]{-15, 39}, array[2]{15, 39}};
    #declare SubspaceEdgeWeights = array[4]{2, 1, 2, 1};
    #declare SubspaceFaces = array[1]{array[4]{-15, -39, 15, 39}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=28)  // 2b22
    #declare SubspaceVerticesPositive = array[2]{21, 39};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[4]{array[2]{-21, -39}, array[2]{21, -39}, array[2]{21, 39}, array[2]{-21, 39}};
    #declare SubspaceEdgeWeights = array[4]{2, 1, 2, 1};
    #declare SubspaceFaces = array[1]{array[4]{21, -39, -21, 39}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=29)  // 2b23
    #declare SubspaceVerticesPositive = array[2]{33, 39};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[4]{array[2]{33, -39}, array[2]{-33, -39}, array[2]{-33, 39}, array[2]{33, 39}};
    #declare SubspaceEdgeWeights = array[4]{1, 2, 1, 2};
    #declare SubspaceFaces = array[1]{array[4]{-33, -39, 33, 39}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=30)  // 2c00
    #declare SubspaceVerticesPositive = array[2]{16, 20};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[4]{array[2]{-16, 20}, array[2]{16, 20}, array[2]{16, -20}, array[2]{-16, -20}};
    #declare SubspaceEdgeWeights = array[4]{2, 2, 2, 2};
    #declare SubspaceFaces = array[1]{array[4]{16, 20, -16, -20}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=31)  // 2c01
    #declare SubspaceVerticesPositive = array[2]{14, 22};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[4]{array[2]{14, -22}, array[2]{14, 22}, array[2]{-14, 22}, array[2]{-14, -22}};
    #declare SubspaceEdgeWeights = array[4]{2, 2, 2, 2};
    #declare SubspaceFaces = array[1]{array[4]{-14, -22, 14, 22}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=32)  // 2c02
    #declare SubspaceVerticesPositive = array[2]{16, 32};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[4]{array[2]{-16, 32}, array[2]{16, 32}, array[2]{16, -32}, array[2]{-16, -32}};
    #declare SubspaceEdgeWeights = array[4]{2, 2, 2, 2};
    #declare SubspaceFaces = array[1]{array[4]{16, 32, -16, -32}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=33)  // 2c03
    #declare SubspaceVerticesPositive = array[2]{20, 32};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[4]{array[2]{20, 32}, array[2]{-20, 32}, array[2]{-20, -32}, array[2]{20, -32}};
    #declare SubspaceEdgeWeights = array[4]{2, 2, 2, 2};
    #declare SubspaceFaces = array[1]{array[4]{-20, 32, 20, -32}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=34)  // 2c04
    #declare SubspaceVerticesPositive = array[2]{14, 34};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[4]{array[2]{14, -34}, array[2]{14, 34}, array[2]{-14, 34}, array[2]{-14, -34}};
    #declare SubspaceEdgeWeights = array[4]{2, 2, 2, 2};
    #declare SubspaceFaces = array[1]{array[4]{-14, -34, 14, 34}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=35)  // 2c05
    #declare SubspaceVerticesPositive = array[2]{22, 34};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[4]{array[2]{-22, -34}, array[2]{-22, 34}, array[2]{22, 34}, array[2]{22, -34}};
    #declare SubspaceEdgeWeights = array[4]{2, 2, 2, 2};
    #declare SubspaceFaces = array[1]{array[4]{22, -34, -22, 34}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=36)  // 2c06
    #declare SubspaceVerticesPositive = array[2]{14, 38};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[4]{array[2]{14, 38}, array[2]{14, -38}, array[2]{-14, -38}, array[2]{-14, 38}};
    #declare SubspaceEdgeWeights = array[4]{2, 2, 2, 2};
    #declare SubspaceFaces = array[1]{array[4]{-14, 38, 14, -38}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=37)  // 2c07
    #declare SubspaceVerticesPositive = array[2]{22, 38};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[4]{array[2]{-22, 38}, array[2]{-22, -38}, array[2]{22, -38}, array[2]{22, 38}};
    #declare SubspaceEdgeWeights = array[4]{2, 2, 2, 2};
    #declare SubspaceFaces = array[1]{array[4]{22, 38, -22, -38}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=38)  // 2c08
    #declare SubspaceVerticesPositive = array[2]{34, 38};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[4]{array[2]{-34, 38}, array[2]{-34, -38}, array[2]{34, -38}, array[2]{34, 38}};
    #declare SubspaceEdgeWeights = array[4]{2, 2, 2, 2};
    #declare SubspaceFaces = array[1]{array[4]{34, 38, -34, -38}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=39)  // 2c09
    #declare SubspaceVerticesPositive = array[2]{16, 40};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[4]{array[2]{-16, -40}, array[2]{16, -40}, array[2]{16, 40}, array[2]{-16, 40}};
    #declare SubspaceEdgeWeights = array[4]{2, 2, 2, 2};
    #declare SubspaceFaces = array[1]{array[4]{16, -40, -16, 40}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=40)  // 2c10
    #declare SubspaceVerticesPositive = array[2]{20, 40};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[4]{array[2]{20, -40}, array[2]{-20, -40}, array[2]{-20, 40}, array[2]{20, 40}};
    #declare SubspaceEdgeWeights = array[4]{2, 2, 2, 2};
    #declare SubspaceFaces = array[1]{array[4]{-20, -40, 20, 40}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=41)  // 2c11
    #declare SubspaceVerticesPositive = array[2]{32, 40};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[4]{array[2]{32, -40}, array[2]{-32, -40}, array[2]{-32, 40}, array[2]{32, 40}};
    #declare SubspaceEdgeWeights = array[4]{2, 2, 2, 2};
    #declare SubspaceFaces = array[1]{array[4]{-32, -40, 32, 40}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=42)  // 2d00
    #declare SubspaceVerticesPositive = array[2]{14, 16};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[4]{array[2]{14, -16}, array[2]{14, 16}, array[2]{-14, 16}, array[2]{-14, -16}};
    #declare SubspaceEdgeWeights = array[4]{1, 3, 1, 3};
    #declare SubspaceFaces = array[1]{array[4]{-14, -16, 14, 16}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=43)  // 2d01
    #declare SubspaceVerticesPositive = array[2]{14, 20};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[4]{array[2]{14, 20}, array[2]{14, -20}, array[2]{-14, -20}, array[2]{-14, 20}};
    #declare SubspaceEdgeWeights = array[4]{3, 1, 3, 1};
    #declare SubspaceFaces = array[1]{array[4]{-14, 20, 14, -20}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=44)  // 2d02
    #declare SubspaceVerticesPositive = array[2]{16, 22};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[4]{array[2]{-16, -22}, array[2]{16, -22}, array[2]{16, 22}, array[2]{-16, 22}};
    #declare SubspaceEdgeWeights = array[4]{3, 1, 3, 1};
    #declare SubspaceFaces = array[1]{array[4]{16, -22, -16, 22}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=45)  // 2d03
    #declare SubspaceVerticesPositive = array[2]{20, 22};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[4]{array[2]{20, -22}, array[2]{-20, -22}, array[2]{-20, 22}, array[2]{20, 22}};
    #declare SubspaceEdgeWeights = array[4]{1, 3, 1, 3};
    #declare SubspaceFaces = array[1]{array[4]{-20, -22, 20, 22}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=46)  // 2d04
    #declare SubspaceVerticesPositive = array[2]{14, 32};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[4]{array[2]{14, 32}, array[2]{14, -32}, array[2]{-14, -32}, array[2]{-14, 32}};
    #declare SubspaceEdgeWeights = array[4]{3, 1, 3, 1};
    #declare SubspaceFaces = array[1]{array[4]{-14, 32, 14, -32}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=47)  // 2d05
    #declare SubspaceVerticesPositive = array[2]{22, 32};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[4]{array[2]{-22, 32}, array[2]{-22, -32}, array[2]{22, -32}, array[2]{22, 32}};
    #declare SubspaceEdgeWeights = array[4]{3, 1, 3, 1};
    #declare SubspaceFaces = array[1]{array[4]{22, 32, -22, -32}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=48)  // 2d06
    #declare SubspaceVerticesPositive = array[2]{16, 34};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[4]{array[2]{-16, -34}, array[2]{16, -34}, array[2]{16, 34}, array[2]{-16, 34}};
    #declare SubspaceEdgeWeights = array[4]{3, 1, 3, 1};
    #declare SubspaceFaces = array[1]{array[4]{16, -34, -16, 34}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=49)  // 2d07
    #declare SubspaceVerticesPositive = array[2]{20, 34};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[4]{array[2]{20, -34}, array[2]{-20, -34}, array[2]{-20, 34}, array[2]{20, 34}};
    #declare SubspaceEdgeWeights = array[4]{3, 1, 3, 1};
    #declare SubspaceFaces = array[1]{array[4]{-20, -34, 20, 34}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=50)  // 2d08
    #declare SubspaceVerticesPositive = array[2]{32, 34};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[4]{array[2]{32, -34}, array[2]{32, 34}, array[2]{-32, 34}, array[2]{-32, -34}};
    #declare SubspaceEdgeWeights = array[4]{1, 3, 1, 3};
    #declare SubspaceFaces = array[1]{array[4]{-32, -34, 32, 34}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=51)  // 2d09
    #declare SubspaceVerticesPositive = array[2]{16, 38};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[4]{array[2]{-16, 38}, array[2]{-16, -38}, array[2]{16, -38}, array[2]{16, 38}};
    #declare SubspaceEdgeWeights = array[4]{3, 1, 3, 1};
    #declare SubspaceFaces = array[1]{array[4]{16, 38, -16, -38}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=52)  // 2d10
    #declare SubspaceVerticesPositive = array[2]{20, 38};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[4]{array[2]{20, 38}, array[2]{20, -38}, array[2]{-20, -38}, array[2]{-20, 38}};
    #declare SubspaceEdgeWeights = array[4]{3, 1, 3, 1};
    #declare SubspaceFaces = array[1]{array[4]{-20, 38, 20, -38}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=53)  // 2d11
    #declare SubspaceVerticesPositive = array[2]{32, 38};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[4]{array[2]{32, 38}, array[2]{32, -38}, array[2]{-32, -38}, array[2]{-32, 38}};
    #declare SubspaceEdgeWeights = array[4]{3, 1, 3, 1};
    #declare SubspaceFaces = array[1]{array[4]{-32, 38, 32, -38}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=54)  // 2d12
    #declare SubspaceVerticesPositive = array[2]{14, 40};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[4]{array[2]{14, -40}, array[2]{-14, -40}, array[2]{-14, 40}, array[2]{14, 40}};
    #declare SubspaceEdgeWeights = array[4]{3, 1, 3, 1};
    #declare SubspaceFaces = array[1]{array[4]{-14, -40, 14, 40}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=55)  // 2d13
    #declare SubspaceVerticesPositive = array[2]{22, 40};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[4]{array[2]{-22, -40}, array[2]{22, -40}, array[2]{22, 40}, array[2]{-22, 40}};
    #declare SubspaceEdgeWeights = array[4]{3, 1, 3, 1};
    #declare SubspaceFaces = array[1]{array[4]{22, -40, -22, 40}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=56)  // 2d14
    #declare SubspaceVerticesPositive = array[2]{34, 40};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[4]{array[2]{-34, -40}, array[2]{34, -40}, array[2]{34, 40}, array[2]{-34, 40}};
    #declare SubspaceEdgeWeights = array[4]{3, 1, 3, 1};
    #declare SubspaceFaces = array[1]{array[4]{34, -40, -34, 40}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=57)  // 2d15
    #declare SubspaceVerticesPositive = array[2]{38, 40};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[4]{array[2]{38, -40}, array[2]{-38, -40}, array[2]{-38, 40}, array[2]{38, 40}};
    #declare SubspaceEdgeWeights = array[4]{1, 3, 1, 3};
    #declare SubspaceFaces = array[1]{array[4]{-38, -40, 38, 40}};
    #declare SubspaceFaceWeights = array[1]{0};
#end
#if (clock=58)  // 3a0
    #declare SubspaceVerticesPositive = array[4]{5, 7, 11, 13};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[12]{array[2]{5, 7}, array[2]{-5, -7}, array[2]{5, 11}, array[2]{-7, 11}, array[2]{-5, -11}, array[2]{7, -11}, array[2]{7, 13}, array[2]{11, 13}, array[2]{-5, 13}, array[2]{5, -13}, array[2]{-7, -13}, array[2]{-11, -13}};
    #declare SubspaceEdgeWeights = array[12]{2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2};
    #declare SubspaceFaces = array[6]{array[4]{7, 5, 11, 13}, array[4]{11, -7, -5, 13}, array[4]{7, -11, -5, 13}, array[4]{5, 11, -7, -13}, array[4]{-7, -5, -11, -13}, array[4]{5, 7, -11, -13}};
    #declare SubspaceFaceWeights = array[6]{1, 1, 1, 1, 1, 1};
#end
#if (clock=59)  // 3a1
    #declare SubspaceVerticesPositive = array[4]{23, 25, 29, 31};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[12]{array[2]{23, 25}, array[2]{-23, -25}, array[2]{23, 29}, array[2]{-25, 29}, array[2]{-23, -29}, array[2]{25, -29}, array[2]{25, 31}, array[2]{29, 31}, array[2]{-23, 31}, array[2]{23, -31}, array[2]{-25, -31}, array[2]{-29, -31}};
    #declare SubspaceEdgeWeights = array[12]{2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2};
    #declare SubspaceFaces = array[6]{array[4]{25, 23, 29, 31}, array[4]{29, -25, -23, 31}, array[4]{25, -29, -23, 31}, array[4]{23, 29, -25, -31}, array[4]{-25, -23, -29, -31}, array[4]{23, 25, -29, -31}};
    #declare SubspaceFaceWeights = array[6]{1, 1, 1, 1, 1, 1};
#end
#if (clock=60)  // 3a2
    #declare SubspaceVerticesPositive = array[4]{17, 19, 35, 37};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[12]{array[2]{17, 19}, array[2]{-17, -19}, array[2]{17, 35}, array[2]{-19, 35}, array[2]{-17, -35}, array[2]{19, -35}, array[2]{19, 37}, array[2]{35, 37}, array[2]{-17, 37}, array[2]{17, -37}, array[2]{-19, -37}, array[2]{-35, -37}};
    #declare SubspaceEdgeWeights = array[12]{2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2};
    #declare SubspaceFaces = array[6]{array[4]{19, 17, 35, 37}, array[4]{35, -19, -17, 37}, array[4]{19, -35, -17, 37}, array[4]{17, 35, -19, -37}, array[4]{-19, -17, -35, -37}, array[4]{17, 19, -35, -37}};
    #declare SubspaceFaceWeights = array[6]{1, 1, 1, 1, 1, 1};
#end
#if (clock=61)  // 3a3
    #declare SubspaceVerticesPositive = array[4]{15, 21, 33, 39};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[12]{array[2]{15, 21}, array[2]{-15, -21}, array[2]{15, 33}, array[2]{-21, 33}, array[2]{-15, -33}, array[2]{21, -33}, array[2]{21, 39}, array[2]{33, 39}, array[2]{-15, 39}, array[2]{15, -39}, array[2]{-21, -39}, array[2]{-33, -39}};
    #declare SubspaceEdgeWeights = array[12]{2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2};
    #declare SubspaceFaces = array[6]{array[4]{21, 15, 33, 39}, array[4]{33, -21, -15, 39}, array[4]{21, -33, -15, 39}, array[4]{15, 33, -21, -39}, array[4]{-21, -15, -33, -39}, array[4]{15, 21, -33, -39}};
    #declare SubspaceFaceWeights = array[6]{1, 1, 1, 1, 1, 1};
#end
#if (clock=62)  // 3b00
    #declare SubspaceVerticesPositive = array[4]{14, 16, 20, 22};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[12]{array[2]{14, 16}, array[2]{-14, -16}, array[2]{14, 20}, array[2]{-16, 20}, array[2]{-14, -20}, array[2]{16, -20}, array[2]{16, 22}, array[2]{20, 22}, array[2]{-14, 22}, array[2]{14, -22}, array[2]{-16, -22}, array[2]{-20, -22}};
    #declare SubspaceEdgeWeights = array[12]{3, 3, 3, 2, 3, 2, 3, 3, 2, 2, 3, 3};
    #declare SubspaceFaces = array[6]{array[4]{-16, -14, -20, -22}, array[4]{20, -16, -14, 22}, array[4]{16, -20, -14, 22}, array[4]{14, 20, -16, -22}, array[4]{16, 14, 20, 22}, array[4]{14, 16, -20, -22}};
    #declare SubspaceFaceWeights = array[6]{2, 1, 1, 1, 2, 1};
#end
#if (clock=63)  // 3b01
    #declare SubspaceVerticesPositive = array[4]{14, 16, 32, 34};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[12]{array[2]{14, 16}, array[2]{-14, -16}, array[2]{14, 32}, array[2]{-16, 32}, array[2]{-14, -32}, array[2]{16, -32}, array[2]{16, 34}, array[2]{32, 34}, array[2]{-14, 34}, array[2]{14, -34}, array[2]{-16, -34}, array[2]{-32, -34}};
    #declare SubspaceEdgeWeights = array[12]{3, 3, 3, 2, 3, 2, 3, 3, 2, 2, 3, 3};
    #declare SubspaceFaces = array[6]{array[4]{32, -16, -14, 34}, array[4]{-16, -14, -32, -34}, array[4]{16, -32, -14, 34}, array[4]{14, 32, -16, -34}, array[4]{14, 16, -32, -34}, array[4]{16, 14, 32, 34}};
    #declare SubspaceFaceWeights = array[6]{1, 2, 1, 1, 1, 2};
#end
#if (clock=64)  // 3b02
    #declare SubspaceVerticesPositive = array[4]{20, 22, 32, 34};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[12]{array[2]{20, 22}, array[2]{-20, -22}, array[2]{20, 32}, array[2]{-22, 32}, array[2]{-20, -32}, array[2]{22, -32}, array[2]{22, 34}, array[2]{32, 34}, array[2]{-20, 34}, array[2]{20, -34}, array[2]{-22, -34}, array[2]{-32, -34}};
    #declare SubspaceEdgeWeights = array[12]{3, 3, 2, 3, 2, 3, 2, 3, 3, 3, 2, 3};
    #declare SubspaceFaces = array[6]{array[4]{22, 20, 32, 34}, array[4]{20, 22, -32, -34}, array[4]{22, -32, -20, 34}, array[4]{20, 32, -22, -34}, array[4]{-22, -20, -32, -34}, array[4]{32, -22, -20, 34}};
    #declare SubspaceFaceWeights = array[6]{1, 2, 1, 1, 1, 2};
#end
#if (clock=65)  // 3b03
    #declare SubspaceVerticesPositive = array[4]{14, 20, 32, 38};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[12]{array[2]{14, 20}, array[2]{-14, -20}, array[2]{14, 32}, array[2]{-20, 32}, array[2]{-14, -32}, array[2]{20, -32}, array[2]{20, 38}, array[2]{32, 38}, array[2]{-14, 38}, array[2]{14, -38}, array[2]{-20, -38}, array[2]{-32, -38}};
    #declare SubspaceEdgeWeights = array[12]{3, 3, 3, 2, 3, 2, 3, 3, 2, 2, 3, 3};
    #declare SubspaceFaces = array[6]{array[4]{32, -20, -14, 38}, array[4]{20, -32, -14, 38}, array[4]{-20, -14, -32, -38}, array[4]{20, 14, 32, 38}, array[4]{14, 20, -32, -38}, array[4]{14, 32, -20, -38}};
    #declare SubspaceFaceWeights = array[6]{1, 1, 2, 2, 1, 1};
#end
#if (clock=66)  // 3b04
    #declare SubspaceVerticesPositive = array[4]{16, 22, 32, 38};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[12]{array[2]{16, 22}, array[2]{-16, -22}, array[2]{16, 32}, array[2]{-22, 32}, array[2]{-16, -32}, array[2]{22, -32}, array[2]{22, 38}, array[2]{32, 38}, array[2]{-16, 38}, array[2]{16, -38}, array[2]{-22, -38}, array[2]{-32, -38}};
    #declare SubspaceEdgeWeights = array[12]{3, 3, 2, 3, 2, 3, 2, 3, 3, 3, 2, 3};
    #declare SubspaceFaces = array[6]{array[4]{22, 16, 32, 38}, array[4]{22, -32, -16, 38}, array[4]{16, 22, -32, -38}, array[4]{32, -22, -16, 38}, array[4]{-22, -16, -32, -38}, array[4]{16, 32, -22, -38}};
    #declare SubspaceFaceWeights = array[6]{1, 1, 2, 2, 1, 1};
#end
#if (clock=67)  // 3b05
    #declare SubspaceVerticesPositive = array[4]{16, 20, 34, 38};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[12]{array[2]{16, 20}, array[2]{-16, -20}, array[2]{16, 34}, array[2]{-20, 34}, array[2]{-16, -34}, array[2]{20, -34}, array[2]{20, 38}, array[2]{34, 38}, array[2]{-16, 38}, array[2]{16, -38}, array[2]{-20, -38}, array[2]{-34, -38}};
    #declare SubspaceEdgeWeights = array[12]{2, 2, 3, 3, 3, 3, 3, 2, 3, 3, 3, 2};
    #declare SubspaceFaces = array[6]{array[4]{20, 16, 34, 38}, array[4]{34, -20, -16, 38}, array[4]{16, 34, -20, -38}, array[4]{20, -34, -16, 38}, array[4]{-20, -16, -34, -38}, array[4]{16, 20, -34, -38}};
    #declare SubspaceFaceWeights = array[6]{1, 1, 2, 2, 1, 1};
#end
#if (clock=68)  // 3b06
    #declare SubspaceVerticesPositive = array[4]{14, 22, 32, 40};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[12]{array[2]{14, 22}, array[2]{-14, -22}, array[2]{14, 32}, array[2]{-22, 32}, array[2]{-14, -32}, array[2]{22, -32}, array[2]{22, 40}, array[2]{32, 40}, array[2]{-14, 40}, array[2]{14, -40}, array[2]{-22, -40}, array[2]{-32, -40}};
    #declare SubspaceEdgeWeights = array[12]{2, 2, 3, 3, 3, 3, 3, 2, 3, 3, 3, 2};
    #declare SubspaceFaces = array[6]{array[4]{22, 14, 32, 40}, array[4]{32, -22, -14, 40}, array[4]{22, -32, -14, 40}, array[4]{14, 32, -22, -40}, array[4]{-22, -14, -32, -40}, array[4]{14, 22, -32, -40}};
    #declare SubspaceFaceWeights = array[6]{1, 1, 2, 2, 1, 1};
#end
#if (clock=69)  // 3b07
    #declare SubspaceVerticesPositive = array[4]{14, 20, 34, 40};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[12]{array[2]{14, 20}, array[2]{-14, -20}, array[2]{14, 34}, array[2]{-20, 34}, array[2]{-14, -34}, array[2]{20, -34}, array[2]{20, 40}, array[2]{34, 40}, array[2]{-14, 40}, array[2]{14, -40}, array[2]{-20, -40}, array[2]{-34, -40}};
    #declare SubspaceEdgeWeights = array[12]{3, 3, 2, 3, 2, 3, 2, 3, 3, 3, 2, 3};
    #declare SubspaceFaces = array[6]{array[4]{20, 14, 34, 40}, array[4]{20, -34, -14, 40}, array[4]{34, -20, -14, 40}, array[4]{14, 20, -34, -40}, array[4]{-20, -14, -34, -40}, array[4]{14, 34, -20, -40}};
    #declare SubspaceFaceWeights = array[6]{1, 1, 2, 2, 1, 1};
#end
#if (clock=70)  // 3b08
    #declare SubspaceVerticesPositive = array[4]{16, 22, 34, 40};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[12]{array[2]{16, 22}, array[2]{-16, -22}, array[2]{16, 34}, array[2]{-22, 34}, array[2]{-16, -34}, array[2]{22, -34}, array[2]{22, 40}, array[2]{34, 40}, array[2]{-16, 40}, array[2]{16, -40}, array[2]{-22, -40}, array[2]{-34, -40}};
    #declare SubspaceEdgeWeights = array[12]{3, 3, 3, 2, 3, 2, 3, 3, 2, 2, 3, 3};
    #declare SubspaceFaces = array[6]{array[4]{34, -22, -16, 40}, array[4]{22, -34, -16, 40}, array[4]{22, 16, 34, 40}, array[4]{-22, -16, -34, -40}, array[4]{16, 22, -34, -40}, array[4]{16, 34, -22, -40}};
    #declare SubspaceFaceWeights = array[6]{1, 1, 2, 2, 1, 1};
#end
#if (clock=71)  // 3b09
    #declare SubspaceVerticesPositive = array[4]{14, 16, 38, 40};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[12]{array[2]{14, 16}, array[2]{-14, -16}, array[2]{14, 38}, array[2]{-16, 38}, array[2]{-14, -38}, array[2]{16, -38}, array[2]{16, 40}, array[2]{38, 40}, array[2]{-14, 40}, array[2]{14, -40}, array[2]{-16, -40}, array[2]{-38, -40}};
    #declare SubspaceEdgeWeights = array[12]{3, 3, 2, 3, 2, 3, 2, 3, 3, 3, 2, 3};
    #declare SubspaceFaces = array[6]{array[4]{16, 14, 38, 40}, array[4]{38, -16, -14, 40}, array[4]{16, -38, -14, 40}, array[4]{14, 38, -16, -40}, array[4]{-16, -14, -38, -40}, array[4]{14, 16, -38, -40}};
    #declare SubspaceFaceWeights = array[6]{1, 2, 1, 1, 1, 2};
#end
#if (clock=72)  // 3b10
    #declare SubspaceVerticesPositive = array[4]{20, 22, 38, 40};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[12]{array[2]{20, 22}, array[2]{-20, -22}, array[2]{20, 38}, array[2]{-22, 38}, array[2]{-20, -38}, array[2]{22, -38}, array[2]{22, 40}, array[2]{38, 40}, array[2]{-20, 40}, array[2]{20, -40}, array[2]{-22, -40}, array[2]{-38, -40}};
    #declare SubspaceEdgeWeights = array[12]{3, 3, 3, 2, 3, 2, 3, 3, 2, 2, 3, 3};
    #declare SubspaceFaces = array[6]{array[4]{38, -22, -20, 40}, array[4]{22, 20, 38, 40}, array[4]{22, -38, -20, 40}, array[4]{20, 38, -22, -40}, array[4]{20, 22, -38, -40}, array[4]{-22, -20, -38, -40}};
    #declare SubspaceFaceWeights = array[6]{1, 2, 1, 1, 1, 2};
#end
#if (clock=73)  // 3b11
    #declare SubspaceVerticesPositive = array[4]{32, 34, 38, 40};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[12]{array[2]{32, 34}, array[2]{-32, -34}, array[2]{32, 38}, array[2]{-34, 38}, array[2]{-32, -38}, array[2]{34, -38}, array[2]{34, 40}, array[2]{38, 40}, array[2]{-32, 40}, array[2]{32, -40}, array[2]{-34, -40}, array[2]{-38, -40}};
    #declare SubspaceEdgeWeights = array[12]{3, 3, 3, 2, 3, 2, 3, 3, 2, 2, 3, 3};
    #declare SubspaceFaces = array[6]{array[4]{34, 32, 38, 40}, array[4]{38, -34, -32, 40}, array[4]{34, -38, -32, 40}, array[4]{32, 38, -34, -40}, array[4]{-34, -32, -38, -40}, array[4]{32, 34, -38, -40}};
    #declare SubspaceFaceWeights = array[6]{2, 1, 1, 1, 2, 1};
#end
