#if (clock=0)  // 1a0
    #declare SubspaceVerticesPositive = array[1]{1};
    #declare SubspaceVertexWeight = 1;
    #declare SubspaceEdges = array[1]{array[2]{1, -1}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=1)  // 1a1
    #declare SubspaceVerticesPositive = array[1]{3};
    #declare SubspaceVertexWeight = 1;
    #declare SubspaceEdges = array[1]{array[2]{3, -3}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=2)  // 1a2
    #declare SubspaceVerticesPositive = array[1]{9};
    #declare SubspaceVertexWeight = 1;
    #declare SubspaceEdges = array[1]{array[2]{9, -9}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=3)  // 1a3
    #declare SubspaceVerticesPositive = array[1]{27};
    #declare SubspaceVertexWeight = 1;
    #declare SubspaceEdges = array[1]{array[2]{27, -27}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=4)  // 1b00
    #declare SubspaceVerticesPositive = array[1]{2};
    #declare SubspaceVertexWeight = 2;
    #declare SubspaceEdges = array[1]{array[2]{2, -2}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=5)  // 1b01
    #declare SubspaceVerticesPositive = array[1]{4};
    #declare SubspaceVertexWeight = 2;
    #declare SubspaceEdges = array[1]{array[2]{4, -4}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=6)  // 1b02
    #declare SubspaceVerticesPositive = array[1]{8};
    #declare SubspaceVertexWeight = 2;
    #declare SubspaceEdges = array[1]{array[2]{8, -8}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=7)  // 1b03
    #declare SubspaceVerticesPositive = array[1]{10};
    #declare SubspaceVertexWeight = 2;
    #declare SubspaceEdges = array[1]{array[2]{10, -10}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=8)  // 1b04
    #declare SubspaceVerticesPositive = array[1]{6};
    #declare SubspaceVertexWeight = 2;
    #declare SubspaceEdges = array[1]{array[2]{6, -6}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=9)  // 1b05
    #declare SubspaceVerticesPositive = array[1]{12};
    #declare SubspaceVertexWeight = 2;
    #declare SubspaceEdges = array[1]{array[2]{12, -12}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=10)  // 1b06
    #declare SubspaceVerticesPositive = array[1]{26};
    #declare SubspaceVertexWeight = 2;
    #declare SubspaceEdges = array[1]{array[2]{26, -26}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=11)  // 1b07
    #declare SubspaceVerticesPositive = array[1]{28};
    #declare SubspaceVertexWeight = 2;
    #declare SubspaceEdges = array[1]{array[2]{28, -28}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=12)  // 1b08
    #declare SubspaceVerticesPositive = array[1]{24};
    #declare SubspaceVertexWeight = 2;
    #declare SubspaceEdges = array[1]{array[2]{24, -24}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=13)  // 1b09
    #declare SubspaceVerticesPositive = array[1]{30};
    #declare SubspaceVertexWeight = 2;
    #declare SubspaceEdges = array[1]{array[2]{30, -30}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=14)  // 1b10
    #declare SubspaceVerticesPositive = array[1]{18};
    #declare SubspaceVertexWeight = 2;
    #declare SubspaceEdges = array[1]{array[2]{18, -18}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=15)  // 1b11
    #declare SubspaceVerticesPositive = array[1]{36};
    #declare SubspaceVertexWeight = 2;
    #declare SubspaceEdges = array[1]{array[2]{36, -36}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=16)  // 1c00
    #declare SubspaceVerticesPositive = array[1]{5};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[1]{array[2]{5, -5}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=17)  // 1c01
    #declare SubspaceVerticesPositive = array[1]{7};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[1]{array[2]{7, -7}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=18)  // 1c02
    #declare SubspaceVerticesPositive = array[1]{11};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[1]{array[2]{11, -11}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=19)  // 1c03
    #declare SubspaceVerticesPositive = array[1]{13};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[1]{array[2]{13, -13}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=20)  // 1c04
    #declare SubspaceVerticesPositive = array[1]{23};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[1]{array[2]{23, -23}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=21)  // 1c05
    #declare SubspaceVerticesPositive = array[1]{25};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[1]{array[2]{25, -25}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=22)  // 1c06
    #declare SubspaceVerticesPositive = array[1]{29};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[1]{array[2]{29, -29}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=23)  // 1c07
    #declare SubspaceVerticesPositive = array[1]{31};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[1]{array[2]{31, -31}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=24)  // 1c08
    #declare SubspaceVerticesPositive = array[1]{17};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[1]{array[2]{17, -17}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=25)  // 1c09
    #declare SubspaceVerticesPositive = array[1]{19};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[1]{array[2]{19, -19}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=26)  // 1c10
    #declare SubspaceVerticesPositive = array[1]{35};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[1]{array[2]{35, -35}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=27)  // 1c11
    #declare SubspaceVerticesPositive = array[1]{37};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[1]{array[2]{37, -37}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=28)  // 1c12
    #declare SubspaceVerticesPositive = array[1]{15};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[1]{array[2]{15, -15}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=29)  // 1c13
    #declare SubspaceVerticesPositive = array[1]{21};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[1]{array[2]{21, -21}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=30)  // 1c14
    #declare SubspaceVerticesPositive = array[1]{33};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[1]{array[2]{33, -33}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=31)  // 1c15
    #declare SubspaceVerticesPositive = array[1]{39};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[1]{array[2]{39, -39}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=32)  // 1d0
    #declare SubspaceVerticesPositive = array[1]{14};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[1]{array[2]{14, -14}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=33)  // 1d1
    #declare SubspaceVerticesPositive = array[1]{16};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[1]{array[2]{16, -16}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=34)  // 1d2
    #declare SubspaceVerticesPositive = array[1]{20};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[1]{array[2]{20, -20}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=35)  // 1d3
    #declare SubspaceVerticesPositive = array[1]{22};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[1]{array[2]{22, -22}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=36)  // 1d4
    #declare SubspaceVerticesPositive = array[1]{32};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[1]{array[2]{32, -32}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=37)  // 1d5
    #declare SubspaceVerticesPositive = array[1]{34};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[1]{array[2]{34, -34}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=38)  // 1d6
    #declare SubspaceVerticesPositive = array[1]{38};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[1]{array[2]{38, -38}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=39)  // 1d7
    #declare SubspaceVerticesPositive = array[1]{40};
    #declare SubspaceVertexWeight = 4;
    #declare SubspaceEdges = array[1]{array[2]{40, -40}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
