#if (clock=0)  // 1a0
    #declare SubspaceVerticesPositive = array[1]{1};
    #declare SubspaceVertexWeight = 1;
    #declare SubspaceEdges = array[1]{array[2]{1, -1}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=1)  // 1a1
    #declare SubspaceVerticesPositive = array[1]{3};
    #declare SubspaceVertexWeight = 1;
    #declare SubspaceEdges = array[1]{array[2]{3, -3}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=2)  // 1a2
    #declare SubspaceVerticesPositive = array[1]{9};
    #declare SubspaceVertexWeight = 1;
    #declare SubspaceEdges = array[1]{array[2]{9, -9}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end

#if (clock=3)  // 1b00
    #declare SubspaceVerticesPositive = array[1]{2};
    #declare SubspaceVertexWeight = 2;
    #declare SubspaceEdges = array[1]{array[2]{2, -2}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=4)  // 1b01
    #declare SubspaceVerticesPositive = array[1]{4};
    #declare SubspaceVertexWeight = 2;
    #declare SubspaceEdges = array[1]{array[2]{4, -4}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=5)  // 1b02
    #declare SubspaceVerticesPositive = array[1]{8};
    #declare SubspaceVertexWeight = 2;
    #declare SubspaceEdges = array[1]{array[2]{8, -8}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=6)  // 1b03
    #declare SubspaceVerticesPositive = array[1]{10};
    #declare SubspaceVertexWeight = 2;
    #declare SubspaceEdges = array[1]{array[2]{10, -10}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=7)  // 1b04
    #declare SubspaceVerticesPositive = array[1]{6};
    #declare SubspaceVertexWeight = 2;
    #declare SubspaceEdges = array[1]{array[2]{6, -6}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=8)  // 1b05
    #declare SubspaceVerticesPositive = array[1]{12};
    #declare SubspaceVertexWeight = 2;
    #declare SubspaceEdges = array[1]{array[2]{12, -12}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end

#if (clock=9)  // 1c00
    #declare SubspaceVerticesPositive = array[1]{5};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[1]{array[2]{5, -5}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=10)  // 1c01
    #declare SubspaceVerticesPositive = array[1]{7};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[1]{array[2]{7, -7}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=11)  // 1c02
    #declare SubspaceVerticesPositive = array[1]{11};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[1]{array[2]{11, -11}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
#if (clock=12)  // 1c03
    #declare SubspaceVerticesPositive = array[1]{13};
    #declare SubspaceVertexWeight = 3;
    #declare SubspaceEdges = array[1]{array[2]{13, -13}};
    #declare SubspaceEdgeWeights = array[1]{0};
#end
